name: Run API test
on:
  push:
    branches:
      - main
  workflow_dispatch: null
  schedule:
    - cron: 30 2 * * *
    - cron: 30 13 * * *
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v6.0.1
      
    - name: install node and npm
      uses: actions/setup-node@v6.1.0
      with:
        node-veriosn: '18'
        
    - name: install newman and html extra
      run: |
        npm install -g newman
        npm install -g newman-reporter-html
        
    - name: run collection
      run: |
        newman run 'Inwarranty-flow Collection Copy 2.postman_collection.json' /
        -e QA.postman_environment.json /
        -r cli,htmlextra
        
    - name: upload newman report
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
        name: newman-artifact-file
        path: newman/*.html
